# Generated by Django 3.2.16 on 2023-06-22 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('company_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('JoinedDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-JoinedDate'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameL', models.CharField(max_length=50)),
                ('passwordL', models.CharField(max_length=100)),
                ('email', models.EmailField(default='customer0@gmail.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(default='std_prof_Img.png', upload_to='photos/%y/%m/%d')),
                ('status', models.BooleanField(default=True)),
                ('createdAcc', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdAcc'],
            },
        ),
    ]
