# Generated by Django 3.2.16 on 2023-05-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('jobTitle', models.CharField(blank=True, max_length=255)),
                ('yearsOfExperience', models.IntegerField(blank=True, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=255)),
                ('subscription', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos')),
                ('points', models.IntegerField(default=0)),
                ('phoneNumber', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('latestActivities', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('youtube', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
