# Generated by Django 3.2.16 on 2023-06-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofileextended_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileextended',
            old_name='lastName',
            new_name='fullName',
        ),
    ]
